[book]
authors = ["Barrett Ray, Leo Larsen, The Sooner Rover Team"]
language = "en"
multilingual = false
src = "src"
title = "The Sooner Rover Team Guidebook"

[output.html]

[output.linkcheck]

[preprocessor.index]
[preprocessor.links] # fixes broken sublinks