[book]
authors = ["Barrett Ray, Leo Larsen, The Sooner Rover Team"]
language = "en"
multilingual = false
src = "src"
title = "The Sooner Rover Team Guidebook"

[build]
use-default-preprocessors = false

[preprocessor.links]

[output.html]

[output.linkcheck]

